#!/usr/bin/env perl
#
# The build-system is Copyright (C) 2017 Alexander Kuleshov <kuleshovmail@gmail.com>,
#
# Github: https://github.com/0xAX/kernel-dev/tree/master/kernel-testing

use strict;
use warnings "all";
use diagnostics -verbose;

use Getopt::Long;

require "./scripts/disk.pm";

BEGIN { $diagnostics::PRETTY = 1 }

exit 0;
